domains:
- domain: johnniecompany.com.br
  type: PRIMARY
  zone: johnniecompany.com.br
- domain: www.johnniecompany.com.br
  type: ALIAS
  zone: johnniecompany.com.br
name: johnnie-company
region: nyc
static_sites:
- build_command: pnpm build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: mateusrodrigues01/johnnie-company
  name: johnnie-company
  output_dir: dist/spa
  routes:
  - path: /
  source_dir: /
